export * from './Forgot-Password/forgot'
export * from './login/login'
export * from './otp-verification/otp'
export * from './Register/register'
export * from './Dashboard/Dashboard'
export * from './main/main'
export * from './Customer/Customer'
export * from './Product/Product'