export * from './Onboarding/Onboarding';
export * from './Getstarted/Getstarted';
export * from './Login/Login';
export * from './ForgotPassword/ForgotPassword';
export * from './OtpVerification/OtpVerification';
export * from './ConfirmNewPassword/ConfirmNewPassword';
export * from './Register/Register';
export * from './Fillprofile/Fillprofile';
export * from './Mainpages';